---
apiVersion: v1
kind: Service
metadata:
  name: pavan99-test-service
  labels:
    username: pavan99
    env: test
spec:
  type: ClusterIP
  selector:
    app: pavan99-test-redis
  ports:
  - name: helloflask
    port: 6379
    targetPort: 6379
