---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pavan99-test-flask
  labels:
    app: pavan99-test-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pavan99-test-flask
  template:
    metadata:
      labels:
        app: pavan99-test-flask
    spec:
      containers:
        - name: pavan99-test-flask
          imagePullPolicy: Always
          image: pavanshukla99/hw5:latest
          env:
          - name: FLASK_APP
            value: "app.py"
          ports:
          - name: http
            containerPort: 5000
