---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pavan99-test-data
  labels:
    username: pavan99
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
