---
apiVersion: v1
kind: Service
metadata:
  name: pavan99-test-flask-service
  labels:
    username: pavan99
    env: test
spec:
  type: ClusterIP
  selector:
    app: pavan99-test-flask
  ports:
  - name: helloflask
    port: 5000
    targetPort: 5000
